service: typescript-serverless-bootstrap

package:
  individually: true

custom:
  ${file(config/custom.yml)}

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-west-1
  stage: ${opt:stage, 'sandbox'}
  iam:
    role:
      statements:
        ${file(config/role-statements/common.yml)}

functions:
  - ${file(config/functions/hello.yml)}

resources:
  - ${file(config/resources/api-gateway.yml)}
