service: typescript-serverless-bootstrap

package:
  individually: true

custom:
  ${file(config/custom.yml)}

plugins:
  - serverless-webpack
  - serverless-deployment-bucket

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-central-1
  stage: ${opt:stage, 'sandbox'}

functions:
  - ${file(config/functions/create-product.yml)}

resources:
  - ${file(config/resources/api-gateway.yml)}
